VIDEO_PATH: './video/1.mp4'
IMG_SIZE: 640
CONF_THRESH: 0.5
IOU_THRESH: 0.45
YOLOV7_PATH: './weights/yolov7.pt'
CLASSES: 0
DEVICE: 'cpu'
TIME_STEP: 0.5
TIME_ALERT: 10
COORDINATE:
  - 318,380,620,777
  - 767,376,1105,778
  - 1193,383,1544,770